sudo: false
language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '10.20.1'
script:
  - npm run lint
  - npm install -g codecov
  - npm run test
  - codecov -f coverage/*.json
after_success:
  - codecov
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/" 